name: Build everparse package (windows)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, windows, X64, opam-2-3]
    steps:
      - uses: actions/checkout@master

      - name: Prepare
        # opam install --deps-only FStar/fstar.opam
        # ^ relying on the fact that F* dependencies are already installed
        if: false
        # Disabling this, I get
        # Error:  Package karamel has no version opam.
        # but karamel.opam should refer to the file? This also did not
        # work with karamel/karamel.opam (without cd'ing).
        shell: C:\cygwin64\bin\bash.exe --login '{0}'
        run: |
          cd $GITHUB_WORKSPACE && eval $(opam env) && cd karamel && sed -i '/"fstar"/d' karamel.opam && opam install --deps-only karamel.opam && opam install hex re sexplib && echo ""

      - name: Build package
        shell: C:\cygwin64\bin\bash.exe --login '{0}'
        run: |
          cd $GITHUB_WORKSPACE && eval $(opam env) && CC=x86_64-w64-mingw32-gcc.exe make nuget-noversion -kj$(nproc) && echo ""

      - uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          path: |
            everparse
          name: everparse
      - uses: actions/upload-artifact@v4
        with:
          path: |
            EverParse*.nupkg
          name: everparse-nupkg

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download and extract artifact
        uses: actions/download-artifact@v4
        with:
          name: everparse
          path: ${{ github.workspace }}\test
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: src\3d\tests
          path: ${{ github.workspace }}\everparse
      - name: Test EverParse
        shell: cmd
        run: |
          ${{ github.workspace }}\test\everparse.cmd ${{ github.workspace }}\everparse\src\3d\tests\Arithmetic.3d ${{ github.workspace }}\everparse\src\3d\tests\FieldDependence0.3d && ${{ github.workspace }}\test\everparse.cmd ${{ github.workspace }}\everparse\src\3d\tests\Comments.3d && ${{ github.workspace }}\test\everparse.cmd --check_hashes inplace ${{ github.workspace }}\everparse\src\3d\tests\Comments.3d
